language: php

sudo: false

php:
  - 5.6
  - 7.0.5
  - 7.0.9
  - 7.0.11
  - 7.0.13

cache:
    - apt

before_install:
 - composer --prefer-source install

script: phpunit --verbose tests/PukoTests.php

notifications:
  email: "diditvelliz@gmail.com"

after_success:
