language: php

os:
  - linux

sudo: false

php:
  - 7.1.19
  - 7.2.8

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1.19

install:
  - composer install --no-interaction
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
    - mkdir -p build/logs
    - ls -al

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
 - travis_retry php coveralls.phar -v

branches:
  only: master

notifications:
  email: "diditvelliz@gmail.com"
  on_success: never
  on_failure: always

cache:
  directories:
  - vendor
  - $HOME/.cache/composer
